[workspace]

members = [
    "mutex",
    "asyncx",
    "macrox",
    "miox",
    "list",
    "grpc",
    "thumbor",
    "allocator",
    "pointer",
    "http",
    "trait_object",
    "gat",
    "hrtb",
    "thread",
    "ser",
    "closure",
]
